server:
  port: ${PORT:222}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  main:
    allow-bean-definition-overriding: true
    
  datasource:
#    url: jdbc:mysql://192.168.1.113:3307/test?useUnicode=true
    url: jdbc:mysql://192.168.167.15:3307/test?useUnicode=true
    username: root
#    password: qweqweqwe2
    password: qlalfqjsghekd
    driver-class-name: org.mariadb.jdbc.Driver
#  data:
#    mongodb:
#      uri: "mongodb://192.168.1.232:27017"
#      database: "ha"