version: '3.1'
services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb2
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "qlalfqjsghekd"
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci