server:
  port: 222

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
  main:
    allow-bean-definition-overriding: true
    
  datasource:
    url: "jdbc:mysql://192.168.1.113:3306/test"
    username: root
    password: qweqweqwe2
    driver-class-name: org.mariadb.jdbc.Driver
#  data:
#    mongodb:
#      uri: "mongodb://192.168.1.232:27017"
#      database: "ha"